# Generated by Django 5.1.7 on 2025-04-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariods16',
            name='apelido',
        ),
        migrations.RemoveField(
            model_name='usuariods16',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='usuariods16',
            name='edv',
        ),
        migrations.RemoveField(
            model_name='usuariods16',
            name='padrinho',
        ),
        migrations.AddField(
            model_name='usuariods16',
            name='animais',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuariods16',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuariods16',
            name='categoria',
            field=models.CharField(choices=[('Ensino fundamental', 'Ensino fundamental'), ('ensino Médio', 'ensino Médio'), ('Ensino superior', 'Ensino superior'), ('Ensino tecnico', 'Ensino tecnico')], default='Ensino fundamental', max_length=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariods16',
            name='endereco',
            field=models.CharField(default='rua sebastiao', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariods16',
            name='idade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuariods16',
            name='nome',
            field=models.CharField(default='Luana', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariods16',
            name='telefone',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
