# Generated by Django 5.1.7 on 2025-03-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('dataHora', models.DateTimeField(auto_now_add=True)),
                ('local', models.TextField()),
                ('categoria', models.CharField(choices=[('Musica', 'Musica'), ('Palestra', 'Palestra'), ('Workshop', 'Workshop')], max_length=9)),
            ],
        ),
    ]
